services:
  marigold:
    image: izdrail/marigold.izdrail.com:latest
    build: .
    ports: ["8000:8000"]
    volumes:
      - marigold-models:/opt/marigold-assets
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  marigold-models:
